import {createAction, props} from "@ngrx/store";

export enum TableActions{
  SET_DATA_TABLE='SET_DATA_TABLE',
  SET_SORT_KEY='SET_SORT_KEY',
  RESET_DB_STORE='RESET_DB_STORE',
  SET_PAGE='SET_PAGE',
  SET_SEARCH_TERM='SET_SEARCH_TERM',
  SET_CURRENT_USER='SET_CURRENT_USER',
  CREATE_NEW_USER='CREATE_NEW_USER',
  IS_MODAL='IS_MODAL',
  IS_FORM='IS_FORM',
}
